// Contrato RPC interno de DFSha (RI-02: entre nodos siempre RPC tipado, nunca REST).
//
// Enlace que especifica: ControlNode <-> DataNode.
// Quién inicia: SIEMPRE el DataNode (RN-12, RD-06). El ControlNode nunca abre una
// conexión hacia un DataNode; las órdenes viajan en la respuesta al heartbeat.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.4
// source: api/dfsha.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandType int32

const (
	CommandType_COMMAND_TYPE_UNSPECIFIED CommandType = 0
	// Copiar un chunk hacia otro DataNode (re-replicación y rebalanceo, Hito 3).
	CommandType_COMMAND_TYPE_COPY_CHUNK CommandType = 1
	// Eliminar un chunk local (recolección de huérfanos y exceso de réplicas).
	CommandType_COMMAND_TYPE_DELETE_CHUNK CommandType = 2
	// Reenviar el inventario completo fuera de ciclo.
	CommandType_COMMAND_TYPE_REPORT_INVENTORY CommandType = 3
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0: "COMMAND_TYPE_UNSPECIFIED",
		1: "COMMAND_TYPE_COPY_CHUNK",
		2: "COMMAND_TYPE_DELETE_CHUNK",
		3: "COMMAND_TYPE_REPORT_INVENTORY",
	}
	CommandType_value = map[string]int32{
		"COMMAND_TYPE_UNSPECIFIED":      0,
		"COMMAND_TYPE_COPY_CHUNK":       1,
		"COMMAND_TYPE_DELETE_CHUNK":     2,
		"COMMAND_TYPE_REPORT_INVENTORY": 3,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_dfsha_proto_enumTypes[0].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_api_dfsha_proto_enumTypes[0]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_api_dfsha_proto_rawDescGZIP(), []int{0}
}

// NodeReport es el reporte periódico de un DataNode (RD-05).
// El inventario completo permite al ControlNode reconstruir el mapa
// chunk -> ubicaciones sin leer su propio disco (RN-03).
type NodeReport struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	NodeId string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Dirección por la que un cliente externo alcanza a este nodo. Se reporta en
	// lugar de deducirse de la conexión porque la dirección interna del contenedor
	// no siempre es alcanzable desde fuera (RD-12).
	AdvertisedEndpoint string `protobuf:"bytes,2,opt,name=advertised_endpoint,json=advertisedEndpoint,proto3" json:"advertised_endpoint,omitempty"`
	CapacityBytes      int64  `protobuf:"varint,3,opt,name=capacity_bytes,json=capacityBytes,proto3" json:"capacity_bytes,omitempty"`
	UsedBytes          int64  `protobuf:"varint,4,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`
	// Inventario completo de chunks presentes en disco. Es la fuente de verdad de
	// las ubicaciones: el DataNode tiene la última palabra sobre lo que tiene.
	ChunkIds []string `protobuf:"bytes,5,rep,name=chunk_ids,json=chunkIds,proto3" json:"chunk_ids,omitempty"`
	// Peticiones en curso, alimenta la función de puntuación de colocación (RD-10).
	InFlight        int64 `protobuf:"varint,6,opt,name=in_flight,json=inFlight,proto3" json:"in_flight,omitempty"`
	TimestampUnixMs int64 `protobuf:"varint,7,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	// En drenado el nodo no acepta escrituras nuevas y no debe elegirse como
	// destino de ninguna asignación (RD-11). En el Hito 2 siempre es false.
	Draining      bool `protobuf:"varint,8,opt,name=draining,proto3" json:"draining,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeReport) Reset() {
	*x = NodeReport{}
	mi := &file_api_dfsha_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeReport) ProtoMessage() {}

func (x *NodeReport) ProtoReflect() protoreflect.Message {
	mi := &file_api_dfsha_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeReport.ProtoReflect.Descriptor instead.
func (*NodeReport) Descriptor() ([]byte, []int) {
	return file_api_dfsha_proto_rawDescGZIP(), []int{0}
}

func (x *NodeReport) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeReport) GetAdvertisedEndpoint() string {
	if x != nil {
		return x.AdvertisedEndpoint
	}
	return ""
}

func (x *NodeReport) GetCapacityBytes() int64 {
	if x != nil {
		return x.CapacityBytes
	}
	return 0
}

func (x *NodeReport) GetUsedBytes() int64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

func (x *NodeReport) GetChunkIds() []string {
	if x != nil {
		return x.ChunkIds
	}
	return nil
}

func (x *NodeReport) GetInFlight() int64 {
	if x != nil {
		return x.InFlight
	}
	return 0
}

func (x *NodeReport) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

func (x *NodeReport) GetDraining() bool {
	if x != nil {
		return x.Draining
	}
	return false
}

type Command struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Type    CommandType            `protobuf:"varint,1,opt,name=type,proto3,enum=dfsha.v1.CommandType" json:"type,omitempty"`
	ChunkId string                 `protobuf:"bytes,2,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	// Destino para COPY_CHUNK, en la forma host:puerto.
	TargetEndpoint string `protobuf:"bytes,3,opt,name=target_endpoint,json=targetEndpoint,proto3" json:"target_endpoint,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_api_dfsha_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_api_dfsha_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_api_dfsha_proto_rawDescGZIP(), []int{1}
}

func (x *Command) GetType() CommandType {
	if x != nil {
		return x.Type
	}
	return CommandType_COMMAND_TYPE_UNSPECIFIED
}

func (x *Command) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *Command) GetTargetEndpoint() string {
	if x != nil {
		return x.TargetEndpoint
	}
	return ""
}

// CommandList es la respuesta al heartbeat. En el Hito 2 viaja siempre vacía: el
// campo existe desde ahora para que la dirección de la comunicación quede fijada
// y el Hito 3 no cambie el contrato.
type CommandList struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Commands []*Command             `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	// Permite al ControlNode ajustar el ritmo de reporte sin reiniciar el DataNode.
	HeartbeatIntervalMs int64 `protobuf:"varint,2,opt,name=heartbeat_interval_ms,json=heartbeatIntervalMs,proto3" json:"heartbeat_interval_ms,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CommandList) Reset() {
	*x = CommandList{}
	mi := &file_api_dfsha_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandList) ProtoMessage() {}

func (x *CommandList) ProtoReflect() protoreflect.Message {
	mi := &file_api_dfsha_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandList.ProtoReflect.Descriptor instead.
func (*CommandList) Descriptor() ([]byte, []int) {
	return file_api_dfsha_proto_rawDescGZIP(), []int{2}
}

func (x *CommandList) GetCommands() []*Command {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *CommandList) GetHeartbeatIntervalMs() int64 {
	if x != nil {
		return x.HeartbeatIntervalMs
	}
	return 0
}

var File_api_dfsha_proto protoreflect.FileDescriptor

const file_api_dfsha_proto_rawDesc = "" +
	"\n" +
	"\x0fapi/dfsha.proto\x12\bdfsha.v1\"\x9e\x02\n" +
	"\n" +
	"NodeReport\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12/\n" +
	"\x13advertised_endpoint\x18\x02 \x01(\tR\x12advertisedEndpoint\x12%\n" +
	"\x0ecapacity_bytes\x18\x03 \x01(\x03R\rcapacityBytes\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\x04 \x01(\x03R\tusedBytes\x12\x1b\n" +
	"\tchunk_ids\x18\x05 \x03(\tR\bchunkIds\x12\x1b\n" +
	"\tin_flight\x18\x06 \x01(\x03R\binFlight\x12*\n" +
	"\x11timestamp_unix_ms\x18\a \x01(\x03R\x0ftimestampUnixMs\x12\x1a\n" +
	"\bdraining\x18\b \x01(\bR\bdraining\"x\n" +
	"\aCommand\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.dfsha.v1.CommandTypeR\x04type\x12\x19\n" +
	"\bchunk_id\x18\x02 \x01(\tR\achunkId\x12'\n" +
	"\x0ftarget_endpoint\x18\x03 \x01(\tR\x0etargetEndpoint\"p\n" +
	"\vCommandList\x12-\n" +
	"\bcommands\x18\x01 \x03(\v2\x11.dfsha.v1.CommandR\bcommands\x122\n" +
	"\x15heartbeat_interval_ms\x18\x02 \x01(\x03R\x13heartbeatIntervalMs*\x8a\x01\n" +
	"\vCommandType\x12\x1c\n" +
	"\x18COMMAND_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17COMMAND_TYPE_COPY_CHUNK\x10\x01\x12\x1d\n" +
	"\x19COMMAND_TYPE_DELETE_CHUNK\x10\x02\x12!\n" +
	"\x1dCOMMAND_TYPE_REPORT_INVENTORY\x10\x032K\n" +
	"\x0fDataNodeService\x128\n" +
	"\tHeartbeat\x12\x14.dfsha.v1.NodeReport\x1a\x15.dfsha.v1.CommandListBAZ?github.com/thomaszambrano/DFS-Topicos-Telematica/internal/pb;pbb\x06proto3"

var (
	file_api_dfsha_proto_rawDescOnce sync.Once
	file_api_dfsha_proto_rawDescData []byte
)

func file_api_dfsha_proto_rawDescGZIP() []byte {
	file_api_dfsha_proto_rawDescOnce.Do(func() {
		file_api_dfsha_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_dfsha_proto_rawDesc), len(file_api_dfsha_proto_rawDesc)))
	})
	return file_api_dfsha_proto_rawDescData
}

var file_api_dfsha_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_dfsha_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_dfsha_proto_goTypes = []any{
	(CommandType)(0),    // 0: dfsha.v1.CommandType
	(*NodeReport)(nil),  // 1: dfsha.v1.NodeReport
	(*Command)(nil),     // 2: dfsha.v1.Command
	(*CommandList)(nil), // 3: dfsha.v1.CommandList
}
var file_api_dfsha_proto_depIdxs = []int32{
	0, // 0: dfsha.v1.Command.type:type_name -> dfsha.v1.CommandType
	2, // 1: dfsha.v1.CommandList.commands:type_name -> dfsha.v1.Command
	1, // 2: dfsha.v1.DataNodeService.Heartbeat:input_type -> dfsha.v1.NodeReport
	3, // 3: dfsha.v1.DataNodeService.Heartbeat:output_type -> dfsha.v1.CommandList
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_dfsha_proto_init() }
func file_api_dfsha_proto_init() {
	if File_api_dfsha_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_dfsha_proto_rawDesc), len(file_api_dfsha_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_dfsha_proto_goTypes,
		DependencyIndexes: file_api_dfsha_proto_depIdxs,
		EnumInfos:         file_api_dfsha_proto_enumTypes,
		MessageInfos:      file_api_dfsha_proto_msgTypes,
	}.Build()
	File_api_dfsha_proto = out.File
	file_api_dfsha_proto_goTypes = nil
	file_api_dfsha_proto_depIdxs = nil
}
